# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrepair',
            name='los',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carrepair',
            name='type_of_repair',
            field=models.CharField(choices=[('A', 'A-oil change'), ('B', 'B-tire repair'), ('C', 'C-engine inspection'), ('D', 'D-tune-up'), ('E', 'E-brake service'), ('F', 'F-oil gasket replacement')], max_length=1, null=True),
        ),
    ]
